[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NETLIFY_SKIP_PLUGIN_NEON = "true"
  NEON_DATABASE_URL = "skip"
